export const RITUAL_TOM_ABI = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'ACTION_PRICE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'color', type: 'string' },
    ],
    name: 'adoptPet',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'feed',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'play',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'sleepPet',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'clean',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'hasAdopted',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getMyPet',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'color', type: 'string' },
          { internalType: 'uint256', name: 'totalExp', type: 'uint256' },
          { internalType: 'uint8', name: 'hunger', type: 'uint8' },
          { internalType: 'uint8', name: 'happiness', type: 'uint8' },
          { internalType: 'uint8', name: 'energy', type: 'uint8' },
          { internalType: 'uint8', name: 'cleanliness', type: 'uint8' },
          { internalType: 'uint256', name: 'adoptedAt', type: 'uint256' },
          { internalType: 'uint256', name: 'updatedAt', type: 'uint256' },
          { internalType: 'bool', name: 'adopted', type: 'bool' },
        ],
        internalType: 'struct RitualTom.Pet',
        name: 'pet',
        type: 'tuple',
      },
      { internalType: 'uint256', name: 'level', type: 'uint256' },
      { internalType: 'uint256', name: 'expInLevel', type: 'uint256' },
      { internalType: 'uint256', name: 'expToNextLevel', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const
